name: CI - Release Candidate

on:
  push:
    tags:
      - 'release/v*'

permissions:
  contents: read

concurrency:
  group: currency-service-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
